import socket
import logging

logging.basicConfig(filename='server.log', level=logging.INFO, format='%(asctime)s %(levelname)-8s %(message)s')

greetings = ["hello", "hey", "hi"]
farewells = ["bye", "goodbye", "see you"]

def generate_response(clientsocket, my_msg, mes_list1 , mes_list2):
    if my_msg in mes_list1:
        response = "Hello!"
        logging.info(f"Autogenerated response: {response}")
        clientsocket.send(response.encode())
    elif my_msg in mes_list2:
        response = "Bye!"
        logging.info(f"Autogenerated response: {response}")
        clientsocket.send(response.encode())
    else:
        response = input("Enter your response: ")
        clientsocket.send(response.encode())

def count_words(clientsocket, my_msg):
    word_count = str(len(my_msg.split()))
    clientsocket.send(word_count.encode())

serversocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

host = socket.gethostname()

port = 12345

serversocket.bind((host, port))

serversocket.listen(1)

while True:
    clientsocket, addr = serversocket.accept()
    logging.info("Got a connection from %s" % str(addr))
    try:
        msg = clientsocket.recv(1024)
        logging.info("Received message: %s" % msg.decode())
        count_words(clientsocket, msg.decode())
        generate_response(clientsocket, msg.decode(), greetings, farewells)
    except OSError as e:
        logging.error(f"Socket error: {e}")
    finally:
        clientsocket.close()